# Generated by Django 6.0.3 on 2026-03-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_timetable_course_remove_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('note', 'Class Note'), ('assignment', 'Assignment Question')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='assignment',
            field=models.ForeignKey(limit_choices_to={'document_type': 'assignment'}, on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='req_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_profiles', to='core.course'),
        ),
    ]
