# Generated by Django 6.0.3 on 2026-03-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_document_type_alter_document_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
